version: '3.8'
services:
  node-red:
    image: nodered/node-red
    container_name: node-red
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - node_red_data:/data
    networks:
      - my_network

  mqttx:
    image: eclipse-mosquitto
    container_name: mqttx
    restart: unless-stopped
    ports:
      - "1883:1883"
    networks:
      - my_network

volumes:
  node_red_data:

networks:
  my_network:
    driver: bridge
